version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  Build-Deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: install dependencies Frontend
          command: |
            npm run frontend:install
      - run:
          name: install dependencies Backend
          command: |
            npm run backend:install
      - run:
          name: Build Frontend
          command: |
            npm run frontend:build
      - run:
          name: Build Backend
          command: |
            npm run backend:build
      # - run:
      #     name: Deploy Frontend
      #     command: |
      #       npm run frontend:deploy
      - run:
          name: Deploy BackEnd
          command: |
            npm run backend:deploy

workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
  deployment:
    jobs:
      # Build & Deploy the project on `Main` branch
      - Build-Deploy:
          filters:
            branches:
              only: master
